// Type definitions for the Car Wash Management System

export type Company = {
  id: string;
  name: string;
  color: string;
};

export type Vehicle = {
  id: string;
  licensePlate: string;
  companyId: string;
  status: 'active' | 'pending' | 'completed' | 'maintenance';
  imageUrl?: string;
  notes?: string;
  createdAt: Date;
  updatedAt: Date;
};

export type WorkType = 
  | 'premium-full'
  | 'exterior-only'
  | 'interior-only'
  | 'disinfection'
  | 'wax'
  | 'detailing';

export type WorkEntry = {
  id: string;
  vehicleId: string;
  date: Date;
  technicianName: string;
  workType: WorkType;
  duration: number; // minutes
  cost: number;
  notes?: string;
  imageUrls?: string[];
  companyId: string;
};

export type DashboardStats = {
  totalVehicles: number;
  todayEntries: number;
  pendingWork: number;
  avgDuration: number;
  company1Count: number;
  company2Count: number;
  completedToday: number;
  revenue: number;
};

export type ChatMessage = {
  id: string;
  role: 'user' | 'assistant';
  content: string;
  timestamp: Date;
  actions?: ChatAction[];
};

export type ChatAction = {
  type: 'bulk-operation' | 'report' | 'analysis' | 'suggestion';
  label: string;
  data?: Record<string, unknown>;
};

// Team Chat Types
export type TeamUser = {
  id: string;
  name: string;
  avatar?: string;
  role: 'staff' | 'washer';
  status: 'online' | 'offline' | 'away';
  lastSeen?: Date;
};

export type TeamMessage = {
  id: string;
  channelId: string;
  senderId: string;
  content: string;
  timestamp: Date;
  edited?: boolean;
  attachments?: MessageAttachment[];
  reactions?: MessageReaction[];
};

export type MessageAttachment = {
  id: string;
  type: 'image' | 'file';
  url: string;
  name: string;
  size?: number;
};

export type MessageReaction = {
  emoji: string;
  userIds: string[];
  count: number;
};

export type ChatChannel = {
  id: string;
  name: string;
  type: 'channel' | 'direct' | 'group';
  description?: string;
  icon?: string;
  participants: string[]; // user IDs
  unreadCount?: number;
  lastMessage?: TeamMessage;
  isPinned?: boolean;
};

export type TypingIndicator = {
  channelId: string;
  userId: string;
  userName: string;
};

// Staff & Shift Management Types
export type Staff = {
  id: string;
  name: string;
  email: string;
  phone: string;
  role: 'washer' | 'staff';
  avatar?: string;
  status: 'active' | 'inactive' | 'on-leave';
  companyId?: string; // Can be assigned to specific company
  skills?: WorkType[]; // Types of work they can do
  createdAt: Date;
};

export type Reservation = {
  id: string;
  vehicleLicensePlate: string;
  companyId: string;
  reservationDate: Date;
  timeSlot: string; // e.g., "09:00-10:00"
  workType: WorkType;
  estimatedDuration: number; // minutes
  status: 'pending' | 'confirmed' | 'completed' | 'cancelled';
  notes?: string;
  uploadedFrom?: string; // "excel" | "manual"
};

export type Shift = {
  id: string;
  staffId: string;
  date: Date;
  startTime: string; // "08:00"
  endTime: string; // "16:00"
  type: 'morning' | 'afternoon' | 'night' | 'full-day';
  status: 'scheduled' | 'confirmed' | 'completed' | 'cancelled';
  assignedReservations: string[]; // Reservation IDs
  autoGenerated: boolean;
  notes?: string;
};

export type LeaveRequest = {
  id: string;
  staffId: string;
  startDate: Date;
  endDate: Date;
  type: 'vacation' | 'sick' | 'personal' | 'emergency';
  status: 'pending' | 'approved' | 'rejected';
  reason?: string;
  approvedBy?: string;
  createdAt: Date;
};

export type ShiftChangeRequest = {
  id: string;
  staffId: string;
  shiftId: string;
  requestType: 'swap' | 'cancel' | 'time-change';
  targetStaffId?: string; // For swap requests
  proposedStartTime?: string;
  proposedEndTime?: string;
  reason: string;
  status: 'pending' | 'approved' | 'rejected';
  createdAt: Date;
};

// Health Check Types
export type HealthCheckStatus = 'healthy' | 'warning' | 'critical' | 'info';

export type HealthCheckIssue = {
  id: string;
  category: 'data-integrity' | 'performance' | 'system' | 'conflicts';
  severity: HealthCheckStatus;
  title: string;
  description: string;
  affectedItems?: string[];
  autoFixable: boolean;
  fixAction?: () => void;
  timestamp: Date;
};

export type HealthCheckResult = {
  status: HealthCheckStatus;
  lastCheck: Date;
  issues: HealthCheckIssue[];
  metrics: {
    totalVehicles: number;
    totalStaff: number;
    totalShifts: number;
    totalReservations: number;
    duplicates: number;
    conflicts: number;
    performanceScore: number; // 0-100
  };
};
